### ISSUE TITLE
base64 encoded gcloud service key

### ISSUE THREAD

**Issue by yannickgranger** [stefda/action-cloud-run#4]
`Your GCLOUD_AUTH secret (or whatever you name it) must be a base64 encoded gcloud service key with the following permissions:

Service Account User
Cloud Run Admin
Storage Admin`

The GUI propose me Json or P12 key. Do you mean the private key of the JWT in a secret named GCLOUD_AUTH ?

**Comment by stefda** [comment]
It would be the JSON key, I'll update the doc to avoid confusion in the future.
