### ISSUE TITLE
Bug: Permission 'iam.serviceaccounts.actAs' denied on service account

### ISSUE THREAD

**Issue by BkrmDahal** [stefda/action-cloud-run#6]
I was getting ``Permission 'iam.serviceaccounts.actAs' denied on service account`` error when I just added 
- Service Account User
- Cloud Run Admin
- Storage Admin

Solution: 
Add addition role:
- Cloud Run Service Agent

**Comment by stefda** [comment]
Thanks @BkrmDahal, permission added to the doc based on your solution.
