### ISSUE TITLE
Env input doesn't work

### ISSUE THREAD

**Issue by gala1234** [stefda/action-cloud-run#7]
If I try to past the env, I'm having the following error:

![image](https://user-images.githubusercontent.com/33252067/95326774-64df9d80-08a3-11eb-9004-c0b4c6d400b2.png)

**Comment by stefda** [comment]
What are you pasting and where?

**Comment by jdegger** [comment]
I'm getting the same things, its because `env` is not defined in the action.yml

**Comment by gala1234** [comment]
Sorry, it was some time ago, I might try it again to confirm.

But basically, I was trying to pass the `env: [path-to-env-file] ` along with the rest of the params, as I wanted to set a variable from this point.

I've been trying to follow the description, it works, but not when setting the `env`


```
  with:
    image: gcr.io/[your-project]/[image]
    service: [your-service]
    project: [your-project]
    region: [gcp-region]
    env: [path-to-env-file]
    service key: ${{ secrets.GCLOUD_AUTH }}
```

**Comment by jdegger** [comment]
I think this should fix the issue: https://github.com/stefda/action-cloud-run/pull/10
